imports:
    - php

filter:
    excluded_paths:
        - docs/
        - tests/
tools:
    php_mess_detector: true
    php_cpd:
        excluded_dirs:
            - docs/
            - tests/
    php_loc:
        excluded_dirs:
            - docs/
            - tests/
    php_pdepend:
        excluded_dirs:
            1: docs/
            2: tests/
